# Generated by Django 4.1.4 on 2022-12-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_name_user_facebook_id_user_facebook_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='facebook_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
