# Generated by Django 4.1.4 on 2022-12-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_facebook_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='facebook_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
